---
godot_install_dir: /opt/godot
godot_symlink_path: /usr/local/bin/godot
# Hardcoded to the latest stable release.
godot_version: "4.6"
godot_download_urls:
  x86_64: "https://downloads.godotengine.org/?flavor=stable&platform=linux.64&slug=linux.x86_64.zip&version={{ godot_version }}"
  arm64: "https://downloads.godotengine.org/?flavor=stable&platform=linux.arm64&slug=linux.arm64.zip&version={{ godot_version }}"
