---
core_packages:
  - tmux
  - fish
  - kitty
  - mpv
  - git
  - git-lfs
  - vim
  - npm
  - python
  - uv
  - lazygit
  - htop
  - btop
  - bandwhich
  - midnight-commander
  - docker
  - docker-compose
  - colima
