---
core_packages:
  - tmux
  - fish
  - kitty
  - mpv
  - git
  - vim
  - python3
  - python3-venv
  - pipx
  - make
  - wget
  - gpg
  - ncdu
  - htop
  - btop
  - mc
  - nfs-common
  - lazygit
  - network-manager
  - wireless-tools
  - net-tools
  - mitmproxy
  - jq
  - rustup
  - wl-clipboard
