---
- name: Ensure user Docker CLI plugin directory exists
  file:
    path: "{{ ansible_env.HOME }}/.docker/cli-plugins"
    state: directory
    mode: "0755"

- name: Link docker-compose CLI plugin
  file:
    src: "{{ homebrew_prefix }}/bin/docker-compose"
    dest: "{{ ansible_env.HOME }}/.docker/cli-plugins/docker-compose"
    state: link
    force: true
